### ISSUE TITLE
zabbix 7 import template TPL-FA-Compute-Hyper-V (1)

### ISSUE THREAD

**Issue by bigbroDOTpro** [R-Studio/Zabbix_Hyper-V_Monitoring#1]
zabbix 7 import template

General parameter "/3/params": incorrect change starting from "last("perf_counter[\Summary of the health of the Hyper-V virtual machine\Critical health]")+last("perf_counter[\Summary of the health of the Hyper-V virtual machine\Health is OK]"))-last("system.run[powershell.exe "((get-vm).State -eq is 'Running').count the "]")".

**Comment by R-Studio** [comment]
Unfortunately I have no time to work on this. 😞 
Maybe it has something to do with the double quotes. I hope this helps.
